version: "3.9"

services:
  app:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py makemigrations users &&
             python manage.py makemigrations api &&
             python manage.py migrate --run-syncdb &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000

    env_file:
      - .env
    volumes:
      - ./backend/app:/app
      - ./data/web:/vol/web
    environment:
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}

